[build]
  command = "CI= npm run build"
  publish = "build"

[context.production]
  environment = { NODE_VERSION = "18.17.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  GENERATE_SOURCEMAP = "false"
